"""Static product catalog for synthetic data generation.

Contains FMCG brand/manufacturer/category pairings representative of the
German supermarket (Rewe, Edeka, Lidl, Aldi).

Each entry is an archetype that generate_products() samples from when building
the synthetic product catalog.

price_range: approximate regular shelf price band in EUR for the smallest size
in the entry's sizes list, based on 2024/2025 Rewe/Edeka pricing.
The generator samples a base_price from this range, then scales it by size
to derive ref_price per product.

sizes: unitless quantities in the natural unit for the product type
(litres for liquids, kg for solids, count for tablets/pouches/bags/nappies).
Must be ordered smallest to largest; sizes[0] is the base for price scaling.
The generator infers the correct unit label and formatting from the descriptor.
"""

from dataclasses import dataclass


@dataclass(frozen=True)
class CatalogEntry:
    """A single product archetype in the static catalog."""

    brand: str
    manufacturer: str
    category: str
    sub_category: str
    price_range: tuple[float, float]
    is_private_label: bool
    descriptors: list[str]
    sizes: list[float]


CATALOG: list[CatalogEntry] = [
    # ------------------------------------------------------------------ #
    # Household Cleaning                                                 #
    # ------------------------------------------------------------------ #
    CatalogEntry(
        brand="Persil",
        manufacturer="Henkel",
        category="Household Cleaning",
        sub_category="Laundry",
        price_range=(5.99, 6.99),
        is_private_label=False,
        descriptors=[
            "Universal Gel",
            "Color Gel",
            "Universal Powder",
            "Color Powder",
            "Black Perfection Gel",
        ],
        sizes=[1.0, 2.0, 3.0, 4.5],
    ),
    CatalogEntry(
        brand="Ariel",
        manufacturer="Procter & Gamble",
        category="Household Cleaning",
        sub_category="Laundry",
        price_range=(5.49, 6.49),
        is_private_label=False,
        descriptors=[
            "Original Gel",
            "Color Gel",
            "Original Powder",
            "All-in-1 Pods",
            "Mountain Spring Gel",
        ],
        sizes=[1.0, 2.0, 3.3, 5.0],
    ),
    CatalogEntry(
        brand="Lenor",
        manufacturer="Procter & Gamble",
        category="Household Cleaning",
        sub_category="Fabric Softener",
        price_range=(1.69, 2.19),
        is_private_label=False,
        descriptors=[
            "Spring Awakening",
            "Summer Breeze",
            "Exotic Bloom",
            "Unstoppables Fresh",
        ],
        sizes=[0.95, 2.0, 3.0],
    ),
    CatalogEntry(
        brand="Silan",
        manufacturer="Henkel",
        category="Household Cleaning",
        sub_category="Fabric Softener",
        price_range=(2.09, 2.49),
        is_private_label=False,
        descriptors=["Soft & Oils", "Fresh Control", "Nature Elements", "Classic"],
        sizes=[0.6, 1.1, 1.45],
    ),
    CatalogEntry(
        brand="Pril",
        manufacturer="Henkel",
        category="Household Cleaning",
        sub_category="Dishwashing",
        price_range=(1.29, 1.69),
        is_private_label=False,
        descriptors=[
            "Original Liquid",
            "Lemon Liquid",
            "Balsam Liquid",
            "Power & Protect Liquid",
        ],
        sizes=[0.45, 0.6, 1.0],
    ),
    CatalogEntry(
        brand="Fairy",
        manufacturer="Procter & Gamble",
        category="Household Cleaning",
        sub_category="Dishwashing",
        price_range=(1.49, 1.99),
        is_private_label=False,
        descriptors=[
            "Original Liquid",
            "Lemon Liquid",
            "Platinum Liquid",
            "Sensitive Liquid",
        ],
        sizes=[0.45, 0.625, 0.9],
    ),
    CatalogEntry(
        brand="Somat",
        manufacturer="Henkel",
        category="Household Cleaning",
        sub_category="Dishwasher Tablets",
        price_range=(5.29, 5.99),
        is_private_label=False,
        descriptors=[
            "Excellence 4in1 Tabs",
            "Gold 12x Tabs",
            "All in 1 Tabs",
            "Extra Tabs",
        ],
        sizes=[27.0, 42.0, 57.0],
    ),
    CatalogEntry(
        brand="Frosch",
        manufacturer="Werner & Mertz",
        category="Household Cleaning",
        sub_category="Surface Cleaning",
        price_range=(2.09, 2.49),
        is_private_label=False,
        descriptors=[
            "Bathroom Cleaner",
            "Kitchen Cleaner",
            "All-Purpose Cleaner",
            "Glass Cleaner",
        ],
        sizes=[0.5, 0.75, 1.0],
    ),
    CatalogEntry(
        brand="Domestos",
        manufacturer="Unilever",
        category="Household Cleaning",
        sub_category="Surface Cleaning",
        price_range=(1.69, 2.09),
        is_private_label=False,
        descriptors=[
            "Thick Bleach Original",
            "Thick Bleach Pine Fresh",
            "WC Kraft-Gel",
            "Spray Bleach",
        ],
        sizes=[0.75, 1.25, 2.0],
    ),
    CatalogEntry(
        brand="ja!",
        manufacturer="Rewe",
        category="Household Cleaning",
        sub_category="Laundry",
        price_range=(2.79, 3.49),
        is_private_label=True,
        descriptors=["Universal Liquid", "Color Liquid", "Universal Powder"],
        sizes=[1.1, 1.5, 5.0],
    ),
    CatalogEntry(
        brand="ja!",
        manufacturer="Rewe",
        category="Household Cleaning",
        sub_category="Dishwashing",
        price_range=(0.69, 0.89),
        is_private_label=True,
        descriptors=["Spülmittel Classic", "Spülmittel Lemon"],
        sizes=[0.5, 1.0],
    ),
    # ------------------------------------------------------------------ #
    # Personal Care                                                      #
    # ------------------------------------------------------------------ #
    CatalogEntry(
        brand="Nivea",
        manufacturer="Beiersdorf",
        category="Personal Care",
        sub_category="Body Care",
        price_range=(1.49, 2.99),
        is_private_label=False,
        descriptors=[
            "Soft Cream",
            "Body Lotion",
            "Shower Gel",
            "Creme",
            "In-Shower Body Lotion",
        ],
        sizes=[0.25, 0.4, 0.625],
    ),
    CatalogEntry(
        brand="Dove",
        manufacturer="Unilever",
        category="Personal Care",
        sub_category="Body Care",
        price_range=(2.09, 3.49),
        is_private_label=False,
        descriptors=[
            "Body Lotion Original",
            "Shower Gel Original",
            "Deeply Nourishing Lotion",
            "Sensitive Shower Gel",
        ],
        sizes=[0.25, 0.4, 0.5],
    ),
    CatalogEntry(
        brand="Oral-B",
        manufacturer="Procter & Gamble",
        category="Personal Care",
        sub_category="Oral Care",
        price_range=(3.99, 4.59),
        is_private_label=False,
        descriptors=[
            "Pro-Expert Whitening Toothpaste",
            "Complete Protection Toothpaste",
            "Cavity Defence Toothpaste",
            "3D White Toothpaste",
        ],
        sizes=[0.075, 0.1],
    ),
    CatalogEntry(
        brand="Colgate",
        manufacturer="Colgate-Palmolive",
        category="Personal Care",
        sub_category="Oral Care",
        price_range=(0.99, 1.49),
        is_private_label=False,
        descriptors=[
            "Total Whitening Toothpaste",
            "Max Fresh Toothpaste",
            "Sensitive Pro-Relief Toothpaste",
            "Triple Action Toothpaste",
        ],
        sizes=[0.075, 0.1],
    ),
    CatalogEntry(
        brand="Schwarzkopf",
        manufacturer="Henkel",
        category="Personal Care",
        sub_category="Hair Care",
        price_range=(1.79, 2.19),
        is_private_label=False,
        descriptors=[
            "Gliss Hair Repair Shampoo",
            "Gliss Conditioner",
            "Schauma Shampoo",
            "Schauma Conditioner",
        ],
        sizes=[0.4, 0.8],
    ),
    CatalogEntry(
        brand="Head & Shoulders",
        manufacturer="Procter & Gamble",
        category="Personal Care",
        sub_category="Hair Care",
        price_range=(3.29, 3.99),
        is_private_label=False,
        descriptors=[
            "Classic Clean Shampoo",
            "Citrus Fresh Shampoo",
            "Sensitive Scalp Shampoo",
            "2in1 Shampoo",
        ],
        sizes=[0.25, 0.3, 0.5],
    ),
    CatalogEntry(
        brand="Pantene",
        manufacturer="Procter & Gamble",
        category="Personal Care",
        sub_category="Hair Care",
        price_range=(3.29, 3.69),
        is_private_label=False,
        descriptors=[
            "Repair & Protect Shampoo",
            "Smooth & Sleek Shampoo",
            "Volume Shampoo",
            "Intensive Repair Conditioner",
        ],
        sizes=[0.3, 0.5],
    ),
    CatalogEntry(
        brand="Fa",
        manufacturer="Henkel",
        category="Personal Care",
        sub_category="Deodorant",
        price_range=(1.79, 2.19),
        is_private_label=False,
        descriptors=[
            "Sport Deodorant Spray",
            "Fresh & Dry Deodorant Spray",
            "Invisible Deodorant Spray",
            "Men Active Spray",
        ],
        sizes=[0.15],
    ),
    CatalogEntry(
        brand="Rexona",
        manufacturer="Unilever",
        category="Personal Care",
        sub_category="Deodorant",
        price_range=(2.49, 2.99),
        is_private_label=False,
        descriptors=[
            "Cotton Dry Deodorant Spray",
            "Active Shield Deodorant Spray",
            "Invisible Aqua Spray",
            "Men Active Fresh Spray",
        ],
        sizes=[0.15],
    ),
    CatalogEntry(
        brand="Gillette",
        manufacturer="Procter & Gamble",
        category="Personal Care",
        sub_category="Shaving",
        price_range=(8.99, 14.99),
        is_private_label=False,
        descriptors=[
            "Fusion5 Razor Blades",
            "Mach3 Razor Blades",
            "Fusion5 Shave Gel",
            "Sensitive Shave Foam",
        ],
        sizes=[4.0, 8.0, 12.0],
    ),
    CatalogEntry(
        brand="Gut & Günstig",
        manufacturer="Edeka",
        category="Personal Care",
        sub_category="Body Care",
        price_range=(0.79, 0.95),
        is_private_label=True,
        descriptors=["Body Lotion", "Shower Gel", "Hand Cream"],
        sizes=[0.3, 0.5],
    ),
    CatalogEntry(
        brand="Gut & Günstig",
        manufacturer="Edeka",
        category="Personal Care",
        sub_category="Oral Care",
        price_range=(0.79, 0.89),
        is_private_label=True,
        descriptors=["Zahncreme Classic", "Zahncreme Whitening"],
        sizes=[0.075, 0.125],
    ),
    # ------------------------------------------------------------------ #
    # Hot Beverages                                                      #
    # ------------------------------------------------------------------ #
    CatalogEntry(
        brand="Nescafé",
        manufacturer="Nestlé",
        category="Hot Beverages",
        sub_category="Instant Coffee",
        price_range=(5.49, 6.49),
        is_private_label=False,
        descriptors=[
            "Classic Instant Coffee",
            "Gold Instant Coffee",
            "Azera Barista Instant",
        ],
        sizes=[0.1, 0.2],
    ),
    CatalogEntry(
        brand="Jacobs",
        manufacturer="JDE Peet's",
        category="Hot Beverages",
        sub_category="Ground Coffee",
        price_range=(6.49, 7.49),
        is_private_label=False,
        descriptors=[
            "Krönung Ground Coffee",
            "Velvet Ground Coffee",
            "Espresso Ground Coffee",
            "Auslese Ground Coffee",
        ],
        sizes=[0.5, 1.0],
    ),
    CatalogEntry(
        brand="Tchibo",
        manufacturer="Tchibo",
        category="Hot Beverages",
        sub_category="Ground Coffee",
        price_range=(6.49, 8.49),
        is_private_label=False,
        descriptors=[
            "Beste Bohne Ground Coffee",
            "Feine Milde Ground Coffee",
            "Espresso Milano Ground Coffee",
            "Barista Caffè Crema Ground Coffee",
        ],
        sizes=[0.5, 1.0],
    ),
    CatalogEntry(
        brand="Melitta",
        manufacturer="Melitta",
        category="Hot Beverages",
        sub_category="Ground Coffee",
        price_range=(8.99, 9.79),
        is_private_label=False,
        descriptors=[
            "Auslese Ground Coffee",
            "Bellacrema Ground Coffee",
            "Espresso Ground Coffee",
            "Naturmild Ground Coffee",
        ],
        sizes=[0.5, 1.0],
    ),
    CatalogEntry(
        brand="Lipton",
        manufacturer="ekaterra",
        category="Hot Beverages",
        sub_category="Tea",
        price_range=(1.19, 1.49),
        is_private_label=False,
        descriptors=[
            "Yellow Label Tea Bags",
            "Green Tea Bags",
            "Earl Grey Tea Bags",
            "Chamomile Tea Bags",
        ],
        sizes=[20.0, 50.0, 100.0],
    ),
    CatalogEntry(
        brand="Teekanne",
        manufacturer="Teekanne",
        category="Hot Beverages",
        sub_category="Tea",
        price_range=(1.99, 2.49),
        is_private_label=False,
        descriptors=[
            "Früchtetee Bags",
            "Pfefferminze Bags",
            "Kamille Bags",
            "TeeFix Black Tea Bags",
        ],
        sizes=[20.0, 40.0],
    ),
    # ------------------------------------------------------------------ #
    # Soft Drinks                                                        #
    # ------------------------------------------------------------------ #
    CatalogEntry(
        brand="Coca-Cola",
        manufacturer="Coca-Cola Europacific Partners",
        category="Soft Drinks",
        sub_category="Cola",
        price_range=(1.29, 1.45),
        is_private_label=False,
        descriptors=["Original Taste", "Zero Sugar", "Light"],
        sizes=[0.5, 1.0, 1.5, 2.0],
    ),
    CatalogEntry(
        brand="Fanta",
        manufacturer="Coca-Cola Europacific Partners",
        category="Soft Drinks",
        sub_category="Fruit Soda",
        price_range=(1.29, 1.45),
        is_private_label=False,
        descriptors=["Orange", "Lemon", "Exotic", "Grape"],
        sizes=[0.5, 1.0, 1.5, 2.0],
    ),
    CatalogEntry(
        brand="Sprite",
        manufacturer="Coca-Cola Europacific Partners",
        category="Soft Drinks",
        sub_category="Lemonade",
        price_range=(1.29, 1.45),
        is_private_label=False,
        descriptors=["Original", "Zero Sugar", "Lemon & Lime"],
        sizes=[0.5, 1.0, 1.5, 2.0],
    ),
    CatalogEntry(
        brand="Red Bull",
        manufacturer="Red Bull GmbH",
        category="Soft Drinks",
        sub_category="Energy Drinks",
        price_range=(1.79, 1.99),
        is_private_label=False,
        descriptors=[
            "Original Energy Drink",
            "Sugar Free Energy Drink",
            "Tropical Edition",
            "Watermelon Edition",
        ],
        sizes=[0.25, 0.355, 0.473],
    ),
    CatalogEntry(
        brand="Capri-Sun",
        manufacturer="Capri-Sun AG",
        category="Soft Drinks",
        sub_category="Juice Drinks",
        price_range=(3.99, 4.59),
        is_private_label=False,
        descriptors=[
            "Multivitamin Pouch",
            "Orange Pouch",
            "Apple Pouch",
            "Safari Fruits Pouch",
        ],
        sizes=[10.0, 20.0],
    ),
    CatalogEntry(
        brand="ja!",
        manufacturer="Rewe",
        category="Soft Drinks",
        sub_category="Cola",
        price_range=(0.59, 0.69),
        is_private_label=True,
        descriptors=["Cola", "Cola Zero"],
        sizes=[1.5, 2.0],
    ),
    # ------------------------------------------------------------------ #
    # Dairy                                                              #
    # ------------------------------------------------------------------ #
    CatalogEntry(
        brand="Müller",
        manufacturer="Theo Müller Group",
        category="Dairy",
        sub_category="Yoghurt",
        price_range=(0.45, 0.59),
        is_private_label=False,
        descriptors=[
            "Joghurt mit der Ecke Strawberry",
            "Joghurt mit der Ecke Peach",
            "Müller Froop Raspberry",
            "Müller Froop Mango",
        ],
        sizes=[0.15, 0.45],
    ),
    CatalogEntry(
        brand="Danone",
        manufacturer="Danone",
        category="Dairy",
        sub_category="Yoghurt",
        price_range=(1.89, 2.19),
        is_private_label=False,
        descriptors=[
            "Activia Natural Yoghurt",
            "Activia Strawberry Yoghurt",
            "Activia Peach Yoghurt",
            "Fruchtzwerge Strawberry",
        ],
        sizes=[0.46, 0.92],
    ),
    CatalogEntry(
        brand="Landliebe",
        manufacturer="Theo Müller Group",
        category="Dairy",
        sub_category="Long Life Milk",
        price_range=(1.29, 1.49),
        is_private_label=False,
        descriptors=[
            "Vollmilch 3.8%",
            "Fettarme Milch 1.5%",
            "Laktosefrei Vollmilch",
        ],
        sizes=[1.0],
    ),
    CatalogEntry(
        brand="Arla",
        manufacturer="Arla Foods",
        category="Dairy",
        sub_category="Long Life Milk",
        price_range=(1.49, 1.69),
        is_private_label=False,
        descriptors=[
            "Bio Weidemilch Vollmilch 3.8%",
            "Bio Weidemilch Fettarm 1.5%",
            "Skyr Natural",
        ],
        sizes=[1.0],
    ),
    CatalogEntry(
        brand="Philadelphia",
        manufacturer="Kraft Heinz",
        category="Dairy",
        sub_category="Cream Cheese",
        price_range=(1.99, 2.49),
        is_private_label=False,
        descriptors=[
            "Original Cream Cheese",
            "Light Cream Cheese",
            "Herbs & Garlic Cream Cheese",
            "Chives Cream Cheese",
        ],
        sizes=[0.175, 0.235, 0.3],
    ),
    CatalogEntry(
        brand="Gut & Günstig",
        manufacturer="Edeka",
        category="Dairy",
        sub_category="Long Life Milk",
        price_range=(0.89, 1.05),
        is_private_label=True,
        descriptors=["Vollmilch 3.5%", "Fettarme Milch 1.5%"],
        sizes=[1.0],
    ),
    CatalogEntry(
        brand="Gut & Günstig",
        manufacturer="Edeka",
        category="Dairy",
        sub_category="Yoghurt",
        price_range=(0.45, 0.55),
        is_private_label=True,
        descriptors=["Naturjoghurt 3.5%", "Erdbeerjoghurt", "Kirschjoghurt"],
        sizes=[0.5, 1.0],
    ),
    # ------------------------------------------------------------------ #
    # Snacks & Confectionery                                             #
    # ------------------------------------------------------------------ #
    CatalogEntry(
        brand="Nutella",
        manufacturer="Ferrero",
        category="Snacks & Confectionery",
        sub_category="Spreads",
        price_range=(3.49, 4.09),
        is_private_label=False,
        descriptors=[
            "Hazelnut Spread",
            "Hazelnut Spread B-ready",
            "Hazelnut Spread & Go",
        ],
        sizes=[0.45, 0.75, 1.0],
    ),
    CatalogEntry(
        brand="Milka",
        manufacturer="Mondelez",
        category="Snacks & Confectionery",
        sub_category="Chocolate",
        price_range=(1.79, 2.19),
        is_private_label=False,
        descriptors=[
            "Alpenmilch Chocolate",
            "Oreo Chocolate Bar",
            "Strawberry Chocolate Bar",
            "Caramel Chocolate Bar",
            "Hazelnut Chocolate Bar",
        ],
        sizes=[0.09, 0.25, 0.3],
    ),
    CatalogEntry(
        brand="Ritter Sport",
        manufacturer="Alfred Ritter GmbH",
        category="Snacks & Confectionery",
        sub_category="Chocolate",
        price_range=(1.79, 2.19),
        is_private_label=False,
        descriptors=[
            "Vollmilch Chocolate",
            "Marzipan Chocolate",
            "Nuss Chocolate",
            "Knusperflakes Chocolate",
            "Pfefferminz Chocolate",
        ],
        sizes=[0.1, 0.25],
    ),
    CatalogEntry(
        brand="Haribo",
        manufacturer="Haribo",
        category="Snacks & Confectionery",
        sub_category="Gummy Candy",
        price_range=(1.09, 1.29),
        is_private_label=False,
        descriptors=[
            "Goldbären Gummies",
            "Starmix Gummies",
            "Tangfastics Gummies",
            "Happy Cola Gummies",
            "Phantasia Gummies",
        ],
        sizes=[0.175, 0.2, 1.0],
    ),
    CatalogEntry(
        brand="Pringles",
        manufacturer="Kellanova",
        category="Snacks & Confectionery",
        sub_category="Crisps",
        price_range=(2.29, 2.69),
        is_private_label=False,
        descriptors=[
            "Original Crisps",
            "Sour Cream & Onion Crisps",
            "Paprika Crisps",
            "Salt & Vinegar Crisps",
        ],
        sizes=[0.165, 0.2],
    ),
    CatalogEntry(
        brand="Lay's",
        manufacturer="PepsiCo",
        category="Snacks & Confectionery",
        sub_category="Crisps",
        price_range=(1.79, 2.19),
        is_private_label=False,
        descriptors=[
            "Classic Crisps",
            "Paprika Crisps",
            "Salt Crisps",
            "Cheese & Onion Crisps",
        ],
        sizes=[0.15, 0.175],
    ),
    # ------------------------------------------------------------------ #
    # Frozen & Chilled Food                                              #
    # ------------------------------------------------------------------ #
    CatalogEntry(
        brand="Dr. Oetker",
        manufacturer="Dr. Oetker",
        category="Frozen & Chilled Food",
        sub_category="Frozen Pizza",
        price_range=(3.29, 3.69),
        is_private_label=False,
        descriptors=[
            "Ristorante Mozzarella Pizza",
            "Ristorante Salame Pizza",
            "Ristorante Funghi Pizza",
            "Ofenfrische Mozzarella Pizza",
        ],
        sizes=[0.32, 0.355, 0.405],
    ),
    CatalogEntry(
        brand="Wagner",
        manufacturer="Nestlé",
        category="Frozen & Chilled Food",
        sub_category="Frozen Pizza",
        price_range=(3.19, 3.59),
        is_private_label=False,
        descriptors=[
            "Steinofen Mozzarella Pizza",
            "Steinofen Salami Pizza",
            "Big City Pizza BBQ",
            "Die Backfrische Salami Pizza",
        ],
        sizes=[0.32, 0.35, 0.43],
    ),
    CatalogEntry(
        brand="Iglo",
        manufacturer="Nomad Foods",
        category="Frozen & Chilled Food",
        sub_category="Frozen Fish",
        price_range=(2.79, 3.19),
        is_private_label=False,
        descriptors=[
            "Fischstäbchen",
            "Schlemmerfilet Bordelaise",
            "Schlemmerfilet Knusper",
            "Rahm-Spinat",
        ],
        sizes=[0.3, 0.45, 0.5],
    ),
    CatalogEntry(
        brand="ja!",
        manufacturer="Rewe",
        category="Frozen & Chilled Food",
        sub_category="Frozen Pizza",
        price_range=(2.79, 3.19),
        is_private_label=True,
        descriptors=["Salami Pizza 3er-Pack", "Mozzarella Pizza 3er-Pack"],
        sizes=[0.9, 1.05],
    ),
    # ------------------------------------------------------------------ #
    # Baby & Child Care                                                  #
    # ------------------------------------------------------------------ #
    CatalogEntry(
        brand="Pampers",
        manufacturer="Procter & Gamble",
        category="Baby & Child Care",
        sub_category="Nappies",
        price_range=(7.49, 7.99),
        is_private_label=False,
        descriptors=[
            "Baby-Dry Size 3",
            "Baby-Dry Size 4",
            "Baby-Dry Pants Size 4",
            "Active Baby Size 3",
            "Harmonie Size 4",
        ],
        sizes=[36.0, 72.0, 108.0],
    ),
    CatalogEntry(
        brand="Hipp",
        manufacturer="Hipp",
        category="Baby & Child Care",
        sub_category="Baby Food",
        price_range=(1.09, 1.29),
        is_private_label=False,
        descriptors=[
            "Karotte-Kartoffel Gläschen",
            "Banane-Apfel Gläschen",
            "Grießbrei Gläschen",
            "Reine Karotten Gläschen",
        ],
        sizes=[0.125, 0.19, 0.25],
    ),
    # ------------------------------------------------------------------ #
    # Pet Care                                                           #
    # ------------------------------------------------------------------ #
    CatalogEntry(
        brand="Whiskas",
        manufacturer="Mars",
        category="Pet Care",
        sub_category="Cat Food",
        price_range=(3.79, 4.29),
        is_private_label=False,
        descriptors=[
            "Adult Poultry Pouches",
            "Adult Tuna Pouches",
            "1+ Chicken Dry Food",
            "Kitten Chicken Pouches",
        ],
        sizes=[12.0, 40.0],
    ),
    CatalogEntry(
        brand="Pedigree",
        manufacturer="Mars",
        category="Pet Care",
        sub_category="Dog Food",
        price_range=(4.29, 4.79),
        is_private_label=False,
        descriptors=[
            "Adult Beef Pouches",
            "Adult Chicken Pouches",
            "Vital Protection Dry Food",
            "DentaStix Daily Dental Sticks",
        ],
        sizes=[12.0, 24.0],
    ),
    CatalogEntry(
        brand="Felix",
        manufacturer="Nestlé Purina",
        category="Pet Care",
        sub_category="Cat Food",
        price_range=(1.59, 1.79),
        is_private_label=False,
        descriptors=[
            "As Good As It Looks Salmon Pouches",
            "As Good As It Looks Chicken Pouches",
            "Crunchy & Soft Adult Dry Food",
        ],
        sizes=[4.0, 12.0, 44.0],
    ),
]
