"""Static product catalog for synthetic data generation.

Contains FMCG brand/manufacturer/category pairings representative of the
German supermarket (Rewe, Edeka, Lidl, Aldi).

Each entry is an archetype that generate_products() samples from when building
the synthetic product catalog.

price_range: approximate regular shelf price band in EUR for the smallest size
in the entry's sizes list, based on 2024/2025 Rewe/Edeka pricing.
The generator samples a base_price from this range, then scales it by size
to derive ref_price per product.

sizes: unitless quantities in the natural unit for the product type
(litres for liquids, kg for solids, count for tablets/pouches/bags/nappies).
Must be ordered smallest to largest; sizes[0] is the base for price scaling.
The generator infers the correct unit label and formatting from the descriptor.
"""

CATALOG: list[dict] = [
    # ------------------------------------------------------------------ #
    # Household Cleaning                                                 #
    # ------------------------------------------------------------------ #
    {
        "brand": "Persil",
        "manufacturer": "Henkel",
        "category": "Household Cleaning",
        "sub_category": "Laundry",
        "price_range": (5.99, 6.99),
        "is_private_label": False,
        "descriptors": [
            "Universal Gel",
            "Color Gel",
            "Universal Powder",
            "Color Powder",
            "Black Perfection Gel",
        ],
        "sizes": [1.0, 2.0, 3.0, 4.5],
    },
    {
        "brand": "Ariel",
        "manufacturer": "Procter & Gamble",
        "category": "Household Cleaning",
        "sub_category": "Laundry",
        "price_range": (5.49, 6.49),
        "is_private_label": False,
        "descriptors": [
            "Original Gel",
            "Color Gel",
            "Original Powder",
            "All-in-1 Pods",
            "Mountain Spring Gel",
        ],
        "sizes": [1.0, 2.0, 3.3, 5.0],
    },
    {
        "brand": "Lenor",
        "manufacturer": "Procter & Gamble",
        "category": "Household Cleaning",
        "sub_category": "Fabric Softener",
        "price_range": (1.69, 2.19),
        "is_private_label": False,
        "descriptors": [
            "Spring Awakening",
            "Summer Breeze",
            "Exotic Bloom",
            "Unstoppables Fresh",
        ],
        "sizes": [0.95, 2.0, 3.0],
    },
    {
        "brand": "Silan",
        "manufacturer": "Henkel",
        "category": "Household Cleaning",
        "sub_category": "Fabric Softener",
        "price_range": (2.09, 2.49),
        "is_private_label": False,
        "descriptors": ["Soft & Oils", "Fresh Control", "Nature Elements", "Classic"],
        "sizes": [0.6, 1.1, 1.45],
    },
    {
        "brand": "Pril",
        "manufacturer": "Henkel",
        "category": "Household Cleaning",
        "sub_category": "Dishwashing",
        "price_range": (1.29, 1.69),
        "is_private_label": False,
        "descriptors": [
            "Original Liquid",
            "Lemon Liquid",
            "Balsam Liquid",
            "Power & Protect Liquid",
        ],
        "sizes": [0.45, 0.6, 1.0],
    },
    {
        "brand": "Fairy",
        "manufacturer": "Procter & Gamble",
        "category": "Household Cleaning",
        "sub_category": "Dishwashing",
        "price_range": (1.49, 1.99),
        "is_private_label": False,
        "descriptors": [
            "Original Liquid",
            "Lemon Liquid",
            "Platinum Liquid",
            "Sensitive Liquid",
        ],
        "sizes": [0.45, 0.625, 0.9],
    },
    {
        "brand": "Somat",
        "manufacturer": "Henkel",
        "category": "Household Cleaning",
        "sub_category": "Dishwasher Tablets",
        "price_range": (5.29, 5.99),
        "is_private_label": False,
        "descriptors": [
            "Excellence 4in1 Tabs",
            "Gold 12x Tabs",
            "All in 1 Tabs",
            "Extra Tabs",
        ],
        "sizes": [27.0, 42.0, 57.0],
    },
    {
        "brand": "Frosch",
        "manufacturer": "Werner & Mertz",
        "category": "Household Cleaning",
        "sub_category": "Surface Cleaning",
        "price_range": (2.09, 2.49),
        "is_private_label": False,
        "descriptors": [
            "Bathroom Cleaner",
            "Kitchen Cleaner",
            "All-Purpose Cleaner",
            "Glass Cleaner",
        ],
        "sizes": [0.5, 0.75, 1.0],
    },
    {
        "brand": "Domestos",
        "manufacturer": "Unilever",
        "category": "Household Cleaning",
        "sub_category": "Surface Cleaning",
        "price_range": (1.69, 2.09),
        "is_private_label": False,
        "descriptors": [
            "Thick Bleach Original",
            "Thick Bleach Pine Fresh",
            "WC Kraft-Gel",
            "Spray Bleach",
        ],
        "sizes": [0.75, 1.25, 2.0],
    },
    {
        "brand": "ja!",
        "manufacturer": "Rewe",
        "category": "Household Cleaning",
        "sub_category": "Laundry",
        "price_range": (2.79, 3.49),
        "is_private_label": True,
        "descriptors": ["Universal Liquid", "Color Liquid", "Universal Powder"],
        "sizes": [1.1, 1.5, 5.0],
    },
    {
        "brand": "ja!",
        "manufacturer": "Rewe",
        "category": "Household Cleaning",
        "sub_category": "Dishwashing",
        "price_range": (0.69, 0.89),
        "is_private_label": True,
        "descriptors": ["Spülmittel Classic", "Spülmittel Lemon"],
        "sizes": [0.5, 1.0],
    },
    # ------------------------------------------------------------------ #
    # Personal Care                                                      #
    # ------------------------------------------------------------------ #
    {
        "brand": "Nivea",
        "manufacturer": "Beiersdorf",
        "category": "Personal Care",
        "sub_category": "Body Care",
        "price_range": (1.49, 2.99),
        "is_private_label": False,
        "descriptors": [
            "Soft Cream",
            "Body Lotion",
            "Shower Gel",
            "Creme",
            "In-Shower Body Lotion",
        ],
        "sizes": [0.25, 0.4, 0.625],
    },
    {
        "brand": "Dove",
        "manufacturer": "Unilever",
        "category": "Personal Care",
        "sub_category": "Body Care",
        "price_range": (2.09, 3.49),
        "is_private_label": False,
        "descriptors": [
            "Body Lotion Original",
            "Shower Gel Original",
            "Deeply Nourishing Lotion",
            "Sensitive Shower Gel",
        ],
        "sizes": [0.25, 0.4, 0.5],
    },
    {
        "brand": "Oral-B",
        "manufacturer": "Procter & Gamble",
        "category": "Personal Care",
        "sub_category": "Oral Care",
        "price_range": (3.99, 4.59),
        "is_private_label": False,
        "descriptors": [
            "Pro-Expert Whitening Toothpaste",
            "Complete Protection Toothpaste",
            "Cavity Defence Toothpaste",
            "3D White Toothpaste",
        ],
        "sizes": [0.075, 0.1],
    },
    {
        "brand": "Colgate",
        "manufacturer": "Colgate-Palmolive",
        "category": "Personal Care",
        "sub_category": "Oral Care",
        "price_range": (0.99, 1.49),
        "is_private_label": False,
        "descriptors": [
            "Total Whitening Toothpaste",
            "Max Fresh Toothpaste",
            "Sensitive Pro-Relief Toothpaste",
            "Triple Action Toothpaste",
        ],
        "sizes": [0.075, 0.1],
    },
    {
        "brand": "Schwarzkopf",
        "manufacturer": "Henkel",
        "category": "Personal Care",
        "sub_category": "Hair Care",
        "price_range": (1.79, 2.19),
        "is_private_label": False,
        "descriptors": [
            "Gliss Hair Repair Shampoo",
            "Gliss Conditioner",
            "Schauma Shampoo",
            "Schauma Conditioner",
        ],
        "sizes": [0.4, 0.8],
    },
    {
        "brand": "Head & Shoulders",
        "manufacturer": "Procter & Gamble",
        "category": "Personal Care",
        "sub_category": "Hair Care",
        "price_range": (3.29, 3.99),
        "is_private_label": False,
        "descriptors": [
            "Classic Clean Shampoo",
            "Citrus Fresh Shampoo",
            "Sensitive Scalp Shampoo",
            "2in1 Shampoo",
        ],
        "sizes": [0.25, 0.3, 0.5],
    },
    {
        "brand": "Pantene",
        "manufacturer": "Procter & Gamble",
        "category": "Personal Care",
        "sub_category": "Hair Care",
        "price_range": (3.29, 3.69),
        "is_private_label": False,
        "descriptors": [
            "Repair & Protect Shampoo",
            "Smooth & Sleek Shampoo",
            "Volume Shampoo",
            "Intensive Repair Conditioner",
        ],
        "sizes": [0.3, 0.5],
    },
    {
        "brand": "Fa",
        "manufacturer": "Henkel",
        "category": "Personal Care",
        "sub_category": "Deodorant",
        "price_range": (1.79, 2.19),
        "is_private_label": False,
        "descriptors": [
            "Sport Deodorant Spray",
            "Fresh & Dry Deodorant Spray",
            "Invisible Deodorant Spray",
            "Men Active Spray",
        ],
        "sizes": [0.15],
    },
    {
        "brand": "Rexona",
        "manufacturer": "Unilever",
        "category": "Personal Care",
        "sub_category": "Deodorant",
        "price_range": (2.49, 2.99),
        "is_private_label": False,
        "descriptors": [
            "Cotton Dry Deodorant Spray",
            "Active Shield Deodorant Spray",
            "Invisible Aqua Spray",
            "Men Active Fresh Spray",
        ],
        "sizes": [0.15],
    },
    {
        "brand": "Gillette",
        "manufacturer": "Procter & Gamble",
        "category": "Personal Care",
        "sub_category": "Shaving",
        "price_range": (8.99, 14.99),
        "is_private_label": False,
        "descriptors": [
            "Fusion5 Razor Blades",
            "Mach3 Razor Blades",
            "Fusion5 Shave Gel",
            "Sensitive Shave Foam",
        ],
        "sizes": [4.0, 8.0, 12.0],
    },
    {
        "brand": "Gut & Günstig",
        "manufacturer": "Edeka",
        "category": "Personal Care",
        "sub_category": "Body Care",
        "price_range": (0.79, 0.95),
        "is_private_label": True,
        "descriptors": ["Body Lotion", "Shower Gel", "Hand Cream"],
        "sizes": [0.3, 0.5],
    },
    {
        "brand": "Gut & Günstig",
        "manufacturer": "Edeka",
        "category": "Personal Care",
        "sub_category": "Oral Care",
        "price_range": (0.79, 0.89),
        "is_private_label": True,
        "descriptors": ["Zahncreme Classic", "Zahncreme Whitening"],
        "sizes": [0.075, 0.125],
    },
    # ------------------------------------------------------------------ #
    # Hot Beverages                                                      #
    # ------------------------------------------------------------------ #
    {
        "brand": "Nescafé",
        "manufacturer": "Nestlé",
        "category": "Hot Beverages",
        "sub_category": "Instant Coffee",
        "price_range": (5.49, 6.49),
        "is_private_label": False,
        "descriptors": [
            "Classic Instant Coffee",
            "Gold Instant Coffee",
            "Azera Barista Instant",
        ],
        "sizes": [0.1, 0.2],
    },
    {
        "brand": "Jacobs",
        "manufacturer": "JDE Peet's",
        "category": "Hot Beverages",
        "sub_category": "Ground Coffee",
        "price_range": (6.49, 7.49),
        "is_private_label": False,
        "descriptors": [
            "Krönung Ground Coffee",
            "Velvet Ground Coffee",
            "Espresso Ground Coffee",
            "Auslese Ground Coffee",
        ],
        "sizes": [0.5, 1.0],
    },
    {
        "brand": "Tchibo",
        "manufacturer": "Tchibo",
        "category": "Hot Beverages",
        "sub_category": "Ground Coffee",
        "price_range": (6.49, 8.49),
        "is_private_label": False,
        "descriptors": [
            "Beste Bohne Ground Coffee",
            "Feine Milde Ground Coffee",
            "Espresso Milano Ground Coffee",
            "Barista Caffè Crema Ground Coffee",
        ],
        "sizes": [0.5, 1.0],
    },
    {
        "brand": "Melitta",
        "manufacturer": "Melitta",
        "category": "Hot Beverages",
        "sub_category": "Ground Coffee",
        "price_range": (8.99, 9.79),
        "is_private_label": False,
        "descriptors": [
            "Auslese Ground Coffee",
            "Bellacrema Ground Coffee",
            "Espresso Ground Coffee",
            "Naturmild Ground Coffee",
        ],
        "sizes": [0.5, 1.0],
    },
    {
        "brand": "Lipton",
        "manufacturer": "ekaterra",
        "category": "Hot Beverages",
        "sub_category": "Tea",
        "price_range": (1.19, 1.49),
        "is_private_label": False,
        "descriptors": [
            "Yellow Label Tea Bags",
            "Green Tea Bags",
            "Earl Grey Tea Bags",
            "Chamomile Tea Bags",
        ],
        "sizes": [20.0, 50.0, 100.0],
    },
    {
        "brand": "Teekanne",
        "manufacturer": "Teekanne",
        "category": "Hot Beverages",
        "sub_category": "Tea",
        "price_range": (1.99, 2.49),
        "is_private_label": False,
        "descriptors": [
            "Früchtetee Bags",
            "Pfefferminze Bags",
            "Kamille Bags",
            "TeeFix Black Tea Bags",
        ],
        "sizes": [20.0, 40.0],
    },
    # ------------------------------------------------------------------ #
    # Soft Drinks                                                        #
    # ------------------------------------------------------------------ #
    {
        "brand": "Coca-Cola",
        "manufacturer": "Coca-Cola Europacific Partners",
        "category": "Soft Drinks",
        "sub_category": "Cola",
        "price_range": (1.29, 1.45),
        "is_private_label": False,
        "descriptors": ["Original Taste", "Zero Sugar", "Light"],
        "sizes": [0.5, 1.0, 1.5, 2.0],
    },
    {
        "brand": "Fanta",
        "manufacturer": "Coca-Cola Europacific Partners",
        "category": "Soft Drinks",
        "sub_category": "Fruit Soda",
        "price_range": (1.29, 1.45),
        "is_private_label": False,
        "descriptors": ["Orange", "Lemon", "Exotic", "Grape"],
        "sizes": [0.5, 1.0, 1.5, 2.0],
    },
    {
        "brand": "Sprite",
        "manufacturer": "Coca-Cola Europacific Partners",
        "category": "Soft Drinks",
        "sub_category": "Lemonade",
        "price_range": (1.29, 1.45),
        "is_private_label": False,
        "descriptors": ["Original", "Zero Sugar", "Lemon & Lime"],
        "sizes": [0.5, 1.0, 1.5, 2.0],
    },
    {
        "brand": "Red Bull",
        "manufacturer": "Red Bull GmbH",
        "category": "Soft Drinks",
        "sub_category": "Energy Drinks",
        "price_range": (1.79, 1.99),
        "is_private_label": False,
        "descriptors": [
            "Original Energy Drink",
            "Sugar Free Energy Drink",
            "Tropical Edition",
            "Watermelon Edition",
        ],
        "sizes": [0.25, 0.355, 0.473],
    },
    {
        "brand": "Capri-Sun",
        "manufacturer": "Capri-Sun AG",
        "category": "Soft Drinks",
        "sub_category": "Juice Drinks",
        "price_range": (3.99, 4.59),
        "is_private_label": False,
        "descriptors": [
            "Multivitamin Pouch",
            "Orange Pouch",
            "Apple Pouch",
            "Safari Fruits Pouch",
        ],
        "sizes": [10.0, 20.0],
    },
    {
        "brand": "ja!",
        "manufacturer": "Rewe",
        "category": "Soft Drinks",
        "sub_category": "Cola",
        "price_range": (0.59, 0.69),
        "is_private_label": True,
        "descriptors": ["Cola", "Cola Zero"],
        "sizes": [1.5, 2.0],
    },
    # ------------------------------------------------------------------ #
    # Dairy                                                              #
    # ------------------------------------------------------------------ #
    {
        "brand": "Müller",
        "manufacturer": "Theo Müller Group",
        "category": "Dairy",
        "sub_category": "Yoghurt",
        "price_range": (0.45, 0.59),
        "is_private_label": False,
        "descriptors": [
            "Joghurt mit der Ecke Strawberry",
            "Joghurt mit der Ecke Peach",
            "Müller Froop Raspberry",
            "Müller Froop Mango",
        ],
        "sizes": [0.15, 0.45],
    },
    {
        "brand": "Danone",
        "manufacturer": "Danone",
        "category": "Dairy",
        "sub_category": "Yoghurt",
        "price_range": (1.89, 2.19),
        "is_private_label": False,
        "descriptors": [
            "Activia Natural Yoghurt",
            "Activia Strawberry Yoghurt",
            "Activia Peach Yoghurt",
            "Fruchtzwerge Strawberry",
        ],
        "sizes": [0.46, 0.92],
    },
    {
        "brand": "Landliebe",
        "manufacturer": "Theo Müller Group",
        "category": "Dairy",
        "sub_category": "Long Life Milk",
        "price_range": (1.29, 1.49),
        "is_private_label": False,
        "descriptors": [
            "Vollmilch 3.8%",
            "Fettarme Milch 1.5%",
            "Laktosefrei Vollmilch",
        ],
        "sizes": [1.0],
    },
    {
        "brand": "Arla",
        "manufacturer": "Arla Foods",
        "category": "Dairy",
        "sub_category": "Long Life Milk",
        "price_range": (1.49, 1.69),
        "is_private_label": False,
        "descriptors": [
            "Bio Weidemilch Vollmilch 3.8%",
            "Bio Weidemilch Fettarm 1.5%",
            "Skyr Natural",
        ],
        "sizes": [1.0],
    },
    {
        "brand": "Philadelphia",
        "manufacturer": "Kraft Heinz",
        "category": "Dairy",
        "sub_category": "Cream Cheese",
        "price_range": (1.99, 2.49),
        "is_private_label": False,
        "descriptors": [
            "Original Cream Cheese",
            "Light Cream Cheese",
            "Herbs & Garlic Cream Cheese",
            "Chives Cream Cheese",
        ],
        "sizes": [0.175, 0.235, 0.3],
    },
    {
        "brand": "Gut & Günstig",
        "manufacturer": "Edeka",
        "category": "Dairy",
        "sub_category": "Long Life Milk",
        "price_range": (0.89, 1.05),
        "is_private_label": True,
        "descriptors": ["Vollmilch 3.5%", "Fettarme Milch 1.5%"],
        "sizes": [1.0],
    },
    {
        "brand": "Gut & Günstig",
        "manufacturer": "Edeka",
        "category": "Dairy",
        "sub_category": "Yoghurt",
        "price_range": (0.45, 0.55),
        "is_private_label": True,
        "descriptors": ["Naturjoghurt 3.5%", "Erdbeerjoghurt", "Kirschjoghurt"],
        "sizes": [0.5, 1.0],
    },
    # ------------------------------------------------------------------ #
    # Snacks & Confectionery                                             #
    # ------------------------------------------------------------------ #
    {
        "brand": "Nutella",
        "manufacturer": "Ferrero",
        "category": "Snacks & Confectionery",
        "sub_category": "Spreads",
        "price_range": (3.49, 4.09),
        "is_private_label": False,
        "descriptors": [
            "Hazelnut Spread",
            "Hazelnut Spread B-ready",
            "Hazelnut Spread & Go",
        ],
        "sizes": [0.45, 0.75, 1.0],
    },
    {
        "brand": "Milka",
        "manufacturer": "Mondelez",
        "category": "Snacks & Confectionery",
        "sub_category": "Chocolate",
        "price_range": (1.79, 2.19),
        "is_private_label": False,
        "descriptors": [
            "Alpenmilch Chocolate",
            "Oreo Chocolate Bar",
            "Strawberry Chocolate Bar",
            "Caramel Chocolate Bar",
            "Hazelnut Chocolate Bar",
        ],
        "sizes": [0.09, 0.25, 0.3],
    },
    {
        "brand": "Ritter Sport",
        "manufacturer": "Alfred Ritter GmbH",
        "category": "Snacks & Confectionery",
        "sub_category": "Chocolate",
        "price_range": (1.79, 2.19),
        "is_private_label": False,
        "descriptors": [
            "Vollmilch Chocolate",
            "Marzipan Chocolate",
            "Nuss Chocolate",
            "Knusperflakes Chocolate",
            "Pfefferminz Chocolate",
        ],
        "sizes": [0.1, 0.25],
    },
    {
        "brand": "Haribo",
        "manufacturer": "Haribo",
        "category": "Snacks & Confectionery",
        "sub_category": "Gummy Candy",
        "price_range": (1.09, 1.29),
        "is_private_label": False,
        "descriptors": [
            "Goldbären Gummies",
            "Starmix Gummies",
            "Tangfastics Gummies",
            "Happy Cola Gummies",
            "Phantasia Gummies",
        ],
        "sizes": [0.175, 0.2, 1.0],
    },
    {
        "brand": "Pringles",
        "manufacturer": "Kellanova",
        "category": "Snacks & Confectionery",
        "sub_category": "Crisps",
        "price_range": (2.29, 2.69),
        "is_private_label": False,
        "descriptors": [
            "Original Crisps",
            "Sour Cream & Onion Crisps",
            "Paprika Crisps",
            "Salt & Vinegar Crisps",
        ],
        "sizes": [0.165, 0.2],
    },
    {
        "brand": "Lay's",
        "manufacturer": "PepsiCo",
        "category": "Snacks & Confectionery",
        "sub_category": "Crisps",
        "price_range": (1.79, 2.19),
        "is_private_label": False,
        "descriptors": [
            "Classic Crisps",
            "Paprika Crisps",
            "Salt Crisps",
            "Cheese & Onion Crisps",
        ],
        "sizes": [0.15, 0.175],
    },
    # ------------------------------------------------------------------ #
    # Frozen & Chilled Food                                              #
    # ------------------------------------------------------------------ #
    {
        "brand": "Dr. Oetker",
        "manufacturer": "Dr. Oetker",
        "category": "Frozen & Chilled Food",
        "sub_category": "Frozen Pizza",
        "price_range": (3.29, 3.69),
        "is_private_label": False,
        "descriptors": [
            "Ristorante Mozzarella Pizza",
            "Ristorante Salame Pizza",
            "Ristorante Funghi Pizza",
            "Ofenfrische Mozzarella Pizza",
        ],
        "sizes": [0.32, 0.355, 0.405],
    },
    {
        "brand": "Wagner",
        "manufacturer": "Nestlé",
        "category": "Frozen & Chilled Food",
        "sub_category": "Frozen Pizza",
        "price_range": (3.19, 3.59),
        "is_private_label": False,
        "descriptors": [
            "Steinofen Mozzarella Pizza",
            "Steinofen Salami Pizza",
            "Big City Pizza BBQ",
            "Die Backfrische Salami Pizza",
        ],
        "sizes": [0.32, 0.35, 0.43],
    },
    {
        "brand": "Iglo",
        "manufacturer": "Nomad Foods",
        "category": "Frozen & Chilled Food",
        "sub_category": "Frozen Fish",
        "price_range": (2.79, 3.19),
        "is_private_label": False,
        "descriptors": [
            "Fischstäbchen",
            "Schlemmerfilet Bordelaise",
            "Schlemmerfilet Knusper",
            "Rahm-Spinat",
        ],
        "sizes": [0.3, 0.45, 0.5],
    },
    {
        "brand": "ja!",
        "manufacturer": "Rewe",
        "category": "Frozen & Chilled Food",
        "sub_category": "Frozen Pizza",
        "price_range": (2.79, 3.19),
        "is_private_label": True,
        "descriptors": ["Salami Pizza 3er-Pack", "Mozzarella Pizza 3er-Pack"],
        "sizes": [0.9, 1.05],
    },
    # ------------------------------------------------------------------ #
    # Baby & Child Care                                                  #
    # ------------------------------------------------------------------ #
    {
        "brand": "Pampers",
        "manufacturer": "Procter & Gamble",
        "category": "Baby & Child Care",
        "sub_category": "Nappies",
        "price_range": (7.49, 7.99),
        "is_private_label": False,
        "descriptors": [
            "Baby-Dry Size 3",
            "Baby-Dry Size 4",
            "Baby-Dry Pants Size 4",
            "Active Baby Size 3",
            "Harmonie Size 4",
        ],
        "sizes": [36.0, 72.0, 108.0],
    },
    {
        "brand": "Hipp",
        "manufacturer": "Hipp",
        "category": "Baby & Child Care",
        "sub_category": "Baby Food",
        "price_range": (1.09, 1.29),
        "is_private_label": False,
        "descriptors": [
            "Karotte-Kartoffel Gläschen",
            "Banane-Apfel Gläschen",
            "Grießbrei Gläschen",
            "Reine Karotten Gläschen",
        ],
        "sizes": [0.125, 0.19, 0.25],
    },
    # ------------------------------------------------------------------ #
    # Pet Care                                                           #
    # ------------------------------------------------------------------ #
    {
        "brand": "Whiskas",
        "manufacturer": "Mars",
        "category": "Pet Care",
        "sub_category": "Cat Food",
        "price_range": (3.79, 4.29),
        "is_private_label": False,
        "descriptors": [
            "Adult Poultry Pouches",
            "Adult Tuna Pouches",
            "1+ Chicken Dry Food",
            "Kitten Chicken Pouches",
        ],
        "sizes": [12.0, 40.0],
    },
    {
        "brand": "Pedigree",
        "manufacturer": "Mars",
        "category": "Pet Care",
        "sub_category": "Dog Food",
        "price_range": (4.29, 4.79),
        "is_private_label": False,
        "descriptors": [
            "Adult Beef Pouches",
            "Adult Chicken Pouches",
            "Vital Protection Dry Food",
            "DentaStix Daily Dental Sticks",
        ],
        "sizes": [12.0, 24.0],
    },
    {
        "brand": "Felix",
        "manufacturer": "Nestlé Purina",
        "category": "Pet Care",
        "sub_category": "Cat Food",
        "price_range": (1.59, 1.79),
        "is_private_label": False,
        "descriptors": [
            "As Good As It Looks Salmon Pouches",
            "As Good As It Looks Chicken Pouches",
            "Crunchy & Soft Adult Dry Food",
        ],
        "sizes": [4.0, 12.0, 44.0],
    },
]
